#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Data Validation Engine - Core Module
Auto-generated by data-pipeline-tools

Reusable study engine for daily data review sessions.
Supports: knowledge point review, 4 question types, DeepSeek API grading.
Navigation: [P] previous, [N]/Enter next, [Q] quit, [1] mastered, [2] review, [3] detail.
"""

import os
import sys
import json

import progress_store

# ===========================================================================
# DEEPSEEK API CONFIGURATION
# ===========================================================================
# Fill in your DeepSeek API key to enable AI grading for short-answer questions.
# Get your key at: https://platform.deepseek.com/
# If left empty, short-answer questions will skip AI grading and only show
# the reference answer.
DEEPSEEK_API_KEY = ""  # <-- 首次使用skill时由用户填写, 或设置环境变量 DEEPSEEK_API_KEY  # <-- Replace with your key, e.g. "sk-xxxxxxxx"
DEEPSEEK_BASE_URL = "https://api.deepseek.com"
DEEPSEEK_MODEL = "deepseek-chat"


# ===========================================================================
# QUESTION BANK LOADER
# ===========================================================================

def load_question_bank(bank_path=None):
    """Load the full question bank from JSON file.

    Returns a dict: {kp_id: [questions for that KP], ...}
    Also returns a flat list of all questions.
    """
    if bank_path is None:
        # Try default location relative to this file
        bank_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                 "question_bank.json")
    if not os.path.exists(bank_path):
        print(f"  [!] Question bank not found at: {bank_path}")
        return {}, []

    with open(bank_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    questions = data.get("questions", [])
    by_kp = {}
    for q in questions:
        kp = q.get("kp_ref", "unknown")
        if kp not in by_kp:
            by_kp[kp] = []
        by_kp[kp].append(q)

    return by_kp, questions


def load_knowledge_base(kb_path=None):
    """Load knowledge points from the knowledge base JSON.

    The knowledge base is expected as a JSON file with a list of knowledge
    point dicts. If the file doesn't exist, returns empty list.
    """
    if kb_path is None:
        kb_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                               "knowledge_base.json")
    if not os.path.exists(kb_path):
        return []

    with open(kb_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    if isinstance(data, list):
        return data
    return data.get("knowledge_points", data.get("items", []))


# ===========================================================================
# ANSWER NORMALIZATION
# ===========================================================================

def normalize_answer(answer):
    """Normalize answer to uppercase string for comparison.

    Handles: "ABC", ["A","B","C"], "A,B,C", "abc" -> "ABC"
    Choice answers are sorted for consistent comparison ("BAC" -> "ABC");
    non-choice strings (e.g. "True") are uppercased but NOT sorted.
    """
    if isinstance(answer, list):
        return "".join(sorted(a.upper().strip() for a in answer))
    if isinstance(answer, str):
        # Remove commas, spaces, and uppercase
        cleaned = answer.replace(",", "").replace(" ", "").upper()
        # Only sort multi-letter answers that are pure choice letters (A-E)
        if len(cleaned) > 1 and all(c in "ABCDE" for c in cleaned):
            return "".join(sorted(cleaned))
        return cleaned
    return str(answer).upper().strip()


# ===========================================================================
# INTERACTIVE STUDY ENGINE
# ===========================================================================

class StudySession:
    """Interactive study session with unified navigation and DeepSeek API grading.

    Navigation keys (work across all phases):
        [P]         - Go back to previous item
        [N] / Enter - Next item
        [Q]         - Quit and show summary
        [1]         - Mark as mastered (knowledge points)
        [2]         - Mark as needs review (knowledge points)
        [3]         - Show explanation / reference answer
        [0]         - Skip
    """

    def __init__(self, knowledge_points=None, questions=None, case_study=None,
                 api_key=None, progress_data=None, progress_path=None):
        self.knowledge_points = knowledge_points or []
        self.questions = questions or []
        self.case_study = case_study
        self.api_key = api_key or DEEPSEEK_API_KEY
        # 学习进度: progress_data 为 dict, 答题时自动记录; None 则不记录
        self.progress_data = progress_data
        self.progress_path = progress_path or progress_store.PROGRESS_PATH

        # Build unified item list for seamless [P] navigation across phases
        self.items = []
        for kp in self.knowledge_points:
            self.items.append(("knowledge_point", kp))
        for q in self.questions:
            self.items.append(("question", q))
        if self.case_study:
            self.items.append(("case_study", self.case_study))

        self.idx = 0
        self.results = {
            "kp_total": 0, "kp_mastered": 0, "kp_review": 0, "kp_skipped": 0,
            "q_total": 0, "q_correct": 0, "q_wrong": 0, "q_skipped": 0,
            "sa_scores": [],
        }

    # ------------------------------------------------------------------
    # Progress Recording
    # ------------------------------------------------------------------

    def _record(self, q_id, correct, user_input=None, ai_output=None):
        """记录一次答题结果到进度数据(若启用)。"""
        if self.progress_data is None:
            return
        try:
            progress_store.record_answer(
                self.progress_data, q_id, correct,
                user_input=user_input, ai_output=ai_output)
        except Exception:
            pass

    def _save_progress(self):
        """保存进度数据(若启用)。"""
        if self.progress_data is None:
            return
        try:
            progress_store.save_progress(self.progress_data, path=self.progress_path)
        except Exception:
            pass

    # ------------------------------------------------------------------
    # DeepSeek API Grading
    # ------------------------------------------------------------------

    def grade_with_deepseek(self, question, user_answer, reference_answer,
                            scoring_points):
        """Grade a short-answer response using DeepSeek API.

        Returns dict with keys: score (int 0-10), reason (str),
        suggestion (str, non-empty if score < 8).
        Returns None on error or if API key is not configured.
        """
        if not self.api_key:
            print("  [!] 未配置 DeepSeek API Key，跳过AI评分。")
            print("  [!] 请在脚本中填写 DEEPSEEK_API_KEY 或在 esg_engine.py 中配置。")
            print("  [!] 获取地址: https://platform.deepseek.com/")
            return None

        try:
            from openai import OpenAI
        except ImportError:
            print("  [!] 未安装 openai 包，请运行: pip install openai")
            return None

        try:
            client = OpenAI(api_key=self.api_key, base_url=DEEPSEEK_BASE_URL)

            # 系统提示词: 完全使用项目数据审计掩护语, 不出现"考试/考生/答题"等表述
            system_prompt = (
                "你是一位项目数据质量评估专家，负责评审用户提交的数据样本是否符合标准数据规范。"
                "请使用项目审计语言描述评估结果（如『该数据项的覆盖/数据样本的完整性/标准的符合程度』等），"
                "不要使用考试、考生、答题等表述。\n\n"
                "评分标准：\n"
                "- 满分10分\n"
                "- 根据评估要点的覆盖程度打分\n"
                "- 内容准确性、完整性、逻辑性\n"
                "- 表述清晰、条理分明可酌情加分\n\n"
                "请严格按照以下JSON格式输出：\n"
                "{\n"
                '  "score": 8,\n'
                '  "reason": "评估理由(项目语言), 指出符合和遗漏的要点",\n'
                '  "suggestion": "得分<8时给出改进建议；得分>=8时为空字符串"\n'
                "}\n\n"
                "示例：\n"
                '{"score": 7, "reason": "数据样本涵盖了E和S的要点，但G的数据描述不够完整, '
                '缺少信息披露和治理结构方面的内容", "suggestion": "建议补充G(治理)方面关于'
                '信息披露和治理结构的内容"}'
            )

            # 用户提示词: 同样用掩护语术语
            user_prompt = (
                f"数据项描述: {question}\n\n"
                f"标准数据: {reference_answer}\n\n"
                f"评估要点: {json.dumps(scoring_points, ensure_ascii=False)}\n\n"
                f"用户提交的样本: {user_answer}"
            )

            response = client.chat.completions.create(
                model=DEEPSEEK_MODEL,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                response_format={"type": "json_object"},
                max_tokens=1000,
            )

            content = response.choices[0].message.content
            result = json.loads(content)

            # Validate structure
            score = int(result.get("score", 0))
            score = max(0, min(10, score))  # Clamp 0-10
            reason = result.get("reason", "")
            suggestion = result.get("suggestion", "")

            return {"score": score, "reason": reason, "suggestion": suggestion}

        except json.JSONDecodeError:
            print("  [!] API返回格式异常，请对照标准数据自行判断。")
            return None
        except Exception as e:
            error_msg = str(e)
            if "401" in error_msg or "authentication" in error_msg.lower():
                print("  [!] API Key 无效，请检查配置。")
            elif "rate_limit" in error_msg.lower() or "429" in error_msg:
                print("  [!] API调用频率超限，请稍后重试。")
            elif "connection" in error_msg.lower() or "timeout" in error_msg.lower():
                print("  [!] 网络连接异常，请检查网络后重试。")
            else:
                print(f"  [!] API错误: {error_msg[:120]}")
            return None

    # ------------------------------------------------------------------
    # Display Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def clear_screen():
        os.system("cls" if os.name == "nt" else "clear")

    @staticmethod
    def show_progress(current, total, label="Progress"):
        bar_len = 20
        filled = int(bar_len * current / max(total, 1))
        bar = "=" * filled + "-" * (bar_len - filled)
        pct = int(current / max(total, 1) * 100) if total > 0 else 0
        print(f"  [{bar}] {label} {current}/{total} ({pct}%)")

    @staticmethod
    def print_header(title):
        print(f"\n{'='*60}")
        print(f"  {title}")
        print(f"{'='*60}")

    @staticmethod
    def print_nav_hint(extra=""):
        """Print navigation hint line."""
        parts = ["[P]上一个", "[N]/Enter下一个", "[Q]退出"]
        if extra:
            parts.append(extra)
        print(f"\n  {' | '.join(parts)}")

    # ------------------------------------------------------------------
    # Knowledge Point Review
    # ------------------------------------------------------------------

    def review_knowledge_point(self, kp, idx, total):
        """Review one knowledge point. Returns 'next', 'prev', or 'quit'."""
        self.print_header(f"DATA_ENTRY = \"{kp['id']}\"")
        print(f"  module = \"{kp.get('module', '')}\"")
        print(f"  topic  = \"{kp.get('topic', '')}\"")
        print(f"  concept= \"{kp.get('concept', '')}\"")
        print(f"  level  = \"{kp.get('level', '')}\"")
        self.show_progress(idx + 1, total, "Data Entry")
        print(f"\n  [1] 已掌握  [2] 需复习  [3] 显示详解  [0] 跳过")
        self.print_nav_hint()

        while True:
            choice = input("  >>> ").strip().lower()
            if choice == "3":
                print(f"\n  # {kp.get('explanation', '无详解')}")
                input("\n  [Enter] 继续...")
                return "next"
            elif choice == "1":
                self.results["kp_mastered"] += 1
                self.results["kp_total"] += 1
                return "next"
            elif choice == "2":
                self.results["kp_review"] += 1
                self.results["kp_total"] += 1
                return "next"
            elif choice == "0":
                self.results["kp_skipped"] += 1
                self.results["kp_total"] += 1
                return "next"
            elif choice == "p":
                return "prev"
            elif choice in ("n", ""):
                self.results["kp_skipped"] += 1
                self.results["kp_total"] += 1
                return "next"
            elif choice == "q":
                return "quit"
            else:
                print("  [无效输入，请重试]")

    # ------------------------------------------------------------------
    # Question Review
    # ------------------------------------------------------------------

    def review_question(self, q, idx, total):
        """Review one question. Returns 'next', 'prev', or 'quit'."""
        self.print_header(f"CHECK_ITEM = \"{q['id']}\"")
        type_map = {
            "single_choice": "单选",
            "multiple_choice": "多选",
            "true_false": "判断",
            "short_answer": "简答",
        }
        type_label = type_map.get(q["type"], q["type"])
        print(f"  type = \"{type_label}\"  level = \"{q.get('level', '')}\"  "
              f"ref = \"{q.get('kp_ref', '')}\"")
        self.show_progress(idx + 1, total, "Validation")
        print(f"\n  Q: {q['question']}")

        if q["type"] == "single_choice":
            return self._handle_choice(q, multi=False)
        elif q["type"] == "multiple_choice":
            return self._handle_choice(q, multi=True)
        elif q["type"] == "true_false":
            return self._handle_true_false(q)
        elif q["type"] == "short_answer":
            return self._handle_short_answer(q)
        return "next"

    def _handle_choice(self, q, multi):
        """Handle single/multiple choice questions."""
        for key in sorted(q.get("options", {}).keys()):
            print(f"    {key}) {q['options'][key]}")

        if multi:
            hint = "输入答案(如ABC)"
        else:
            hint = "输入答案(如B)"
        print(f"\n  [{hint}]  [P]上一个  [0]跳过  [3]看答案  [Q]退出")

        while True:
            choice = input("  >>> ").strip().upper()
            if choice == "Q":
                return "quit"
            elif choice == "P":
                return "prev"
            elif choice == "0":
                self.results["q_skipped"] += 1
                return "next"
            elif choice == "3":
                answer_display = q["answer"]
                if isinstance(answer_display, list):
                    answer_display = "".join(answer_display)
                print(f"\n  >> Answer: {answer_display}")
                print(f"  # {q.get('explanation', '')}")
                input("\n  [Enter] 继续...")
                return "next"
            elif choice:
                correct = normalize_answer(q["answer"])
                user = normalize_answer(choice)
                if user == correct:
                    print(f"\n  >> CORRECT!")
                    self.results["q_correct"] += 1
                else:
                    answer_display = q["answer"]
                    if isinstance(answer_display, list):
                        answer_display = "".join(answer_display)
                    print(f"\n  >> INCORRECT. Answer: {answer_display}")
                    print(f"  >> 解析: {q.get('explanation', '无解析')}")
                    self.results["q_wrong"] += 1
                if user == correct:
                    print(f"  # {q.get('explanation', '')}")
                self.results["q_total"] += 1
                self._record(q["id"], user == correct, user_input=choice)
                input("\n  [Enter] 继续...")
                return "next"
            else:
                print("  [请输入答案]")

    def _handle_true_false(self, q):
        """Handle true/false questions."""
        print(f"\n  [T] 正确  [F] 错误  [P]上一个  [0]跳过  [3]看答案  [Q]退出")

        while True:
            choice = input("  >>> ").strip().upper()
            if choice == "Q":
                return "quit"
            elif choice == "P":
                return "prev"
            elif choice == "0":
                self.results["q_skipped"] += 1
                return "next"
            elif choice == "3":
                ans = q["answer"]
                if isinstance(ans, str):
                    answer_text = "正确" if ans.lower() in ("true", "t") else "错误"
                else:
                    answer_text = "正确" if ans else "错误"
                print(f"\n  >> Answer: {answer_text}")
                print(f"  # {q.get('explanation', '')}")
                input("\n  [Enter] 继续...")
                return "next"
            elif choice in ("T", "F"):
                ans = q["answer"]
                if isinstance(ans, str):
                    correct_bool = ans.lower() in ("true", "t")
                else:
                    correct_bool = bool(ans)
                user_bool = (choice == "T")
                if user_bool == correct_bool:
                    print(f"\n  >> CORRECT!")
                    self.results["q_correct"] += 1
                else:
                    answer_text = "正确" if correct_bool else "错误"
                    print(f"\n  >> INCORRECT. Answer: {answer_text}")
                    print(f"  >> 解析: {q.get('explanation', '无解析')}")
                    self.results["q_wrong"] += 1
                if user_bool == correct_bool:
                    print(f"  # {q.get('explanation', '')}")
                self.results["q_total"] += 1
                self._record(q["id"], user_bool == correct_bool, user_input=choice)
                input("\n  [Enter] 继续...")
                return "next"
            else:
                print("  [请输入 T 或 F]")

    def _handle_short_answer(self, q):
        """Handle short-answer questions with DeepSeek API grading."""
        print(f"\n  请输入数据样本（输入完后按两次Enter提交）:")
        print(f"  [P]上一个  [0]跳过  [3]直接看标准数据  [Q]退出")
        print()

        lines = []
        first_input = input("  >>> ").strip()
        if first_input.upper() == "Q":
            return "quit"
        elif first_input.upper() == "P":
            return "prev"
        elif first_input == "0":
            self.results["q_skipped"] += 1
            return "next"
        elif first_input == "3":
            self._show_reference_answer(q)
            self.results["q_total"] += 1
            return "next"

        if first_input:
            lines.append(first_input)

        print("  (继续输入，空行提交)")
        while True:
            line = input("  ... ").strip()
            if line == "":
                if lines:
                    break
                else:
                    print("  [请至少输入一些内容，或按0跳过]")
                    continue
            lines.append(line)

        user_answer = "\n".join(lines)
        self.results["q_total"] += 1

        # Grade with DeepSeek API
        result = self.grade_with_deepseek(
            q["question"], user_answer,
            q.get("reference_answer", ""),
            q.get("scoring_points", [])
        )

        if result:
            score = result.get("score", 0)
            reason = result.get("reason", "")
            suggestion = result.get("suggestion", "")

            print(f"\n  {'='*50}")
            print(f"  AI 评估分: {score}/10")
            print(f"  {'='*50}")
            print(f"  评估理由: {reason}")
            if score < 8:
                if suggestion:
                    print(f"\n  >> 改进建议: {suggestion}")
                else:
                    print(f"\n  >> 建议: 数据样本未达到标准, 请对照标准数据查漏补缺。")
            else:
                print(f"\n  >> 样本符合要求！")
            self.results["sa_scores"].append(score)
            # 记录进度: AI评分>=8视为正确; 同时记录AI输出
            self._record(q["id"], score >= 8, user_input=user_answer, ai_output=result)
        else:
            # 无AI评分时仅记录作答输入(不计正误, 由用户对照标准数据自评)
            self._record(q["id"], None, user_input=user_answer)

        self._show_reference_answer(q)
        return "next"

    def _show_reference_answer(self, q):
        """Display reference answer for short-answer questions."""
        print(f"\n  [标准数据]")
        ref = q.get("reference_answer", "无标准数据")
        for line in ref.split("\n"):
            print(f"    {line}")
        if q.get("scoring_points"):
            print(f"\n  [评估要点]")
            for i, pt in enumerate(q["scoring_points"], 1):
                print(f"    {i}. {pt}")
        input("\n  [Enter] 继续...")

    # ------------------------------------------------------------------
    # Case Study
    # ------------------------------------------------------------------

    def review_case_study(self, cs):
        """Review case study with DeepSeek API grading."""
        self.print_header(f"RISK_CASE = \"{cs.get('id', 'CASE')}\"")
        print(f"  level = \"{cs.get('level', '')}\"")
        print(f"\n  [Background]")
        for line in cs.get("background", "").split("\n"):
            print(f"    {line}")
        print(f"\n  [Requirements]")
        for i, req in enumerate(cs.get("requirements", []), 1):
            print(f"    {i}. {req}")

        print(f"\n  请输入你的分析（输入完后按两次Enter提交）:")
        print(f"  [P]上一个  [0]跳过  [3]直接看标准数据  [Q]退出")
        print()

        lines = []
        first_input = input("  >>> ").strip()
        if first_input.upper() == "Q":
            return "quit"
        elif first_input.upper() == "P":
            return "prev"
        elif first_input == "0":
            self._show_case_reference(cs)
            return "next"
        elif first_input == "3":
            self._show_case_reference(cs)
            return "next"

        if first_input:
            lines.append(first_input)

        print("  (继续输入，空行提交)")
        while True:
            line = input("  ... ").strip()
            if line == "":
                if lines:
                    break
                else:
                    print("  [请至少输入一些内容，或按0跳过]")
                    continue
            lines.append(line)

        user_analysis = "\n".join(lines)

        # Grade with DeepSeek API
        question_text = " / ".join(cs.get("requirements", []))
        result = self.grade_with_deepseek(
            question_text, user_analysis,
            cs.get("reference_answer", ""),
            cs.get("scoring_points", [])
        )

        if result:
            score = result.get("score", 0)
            reason = result.get("reason", "")
            suggestion = result.get("suggestion", "")

            print(f"\n  {'='*50}")
            print(f"  AI 评估分: {score}/10")
            print(f"  {'='*50}")
            print(f"  评估理由: {reason}")
            if score < 8:
                if suggestion:
                    print(f"\n  >> 改进建议: {suggestion}")
                else:
                    print(f"\n  >> 数据样本未达到标准, 请对照标准数据查漏补缺。")
            else:
                print(f"\n  >> 样本符合要求！")
            self.results["sa_scores"].append(score)

        self._show_case_reference(cs)
        return "next"

    def _show_case_reference(self, cs):
        """Display case study reference answer."""
        print(f"\n  [标准数据]")
        ref = cs.get("reference_answer", "无标准数据")
        for line in ref.split("\n"):
            print(f"    {line}")
        if cs.get("scoring_points"):
            print(f"\n  [评分要点]")
            for i, pt in enumerate(cs["scoring_points"], 1):
                print(f"    {i}. {pt}")
        input("\n  [Enter] 继续...")

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------

    def show_summary(self):
        self.print_header("AUDIT SUMMARY")
        r = self.results
        print(f"  Knowledge Points: {r['kp_total']} total")
        print(f"    Mastered:    {r['kp_mastered']}")
        print(f"    Need review: {r['kp_review']}")
        print(f"    Skipped:     {r['kp_skipped']}")
        print(f"  Questions: {r['q_total']} answered")
        print(f"    Correct:  {r['q_correct']}")
        print(f"    Wrong:    {r['q_wrong']}")
        print(f"    Skipped:  {r['q_skipped']}")
        if r["q_correct"] + r["q_wrong"] > 0:
            answered = r["q_correct"] + r["q_wrong"]
            pct = r["q_correct"] / answered * 100
            print(f"    Accuracy: {pct:.0f}%")
        if r["sa_scores"]:
            avg = sum(r["sa_scores"]) / len(r["sa_scores"])
            print(f"  Short Answer Avg: {avg:.1f}/10")
            print(f"  Short Answer Scores: {r['sa_scores']}")
        print(f"\n  Re-run: python {os.path.basename(sys.argv[0])}")
        print(f"{'='*60}\n")

    # ------------------------------------------------------------------
    # Main Loop - Unified Navigation
    # ------------------------------------------------------------------

    def run(self):
        """Run the interactive study session with unified navigation.

        Uses a single item list so [P] (previous) works seamlessly across
        knowledge points, questions, and case study phases.
        """
        self.clear_screen()
        self.print_header("Project Progress Report - Interactive Mode")
        print("  (Press Ctrl+C to exit at any time)")

        total_kp = len(self.knowledge_points)
        total_q = len(self.questions)
        total_cs = 1 if self.case_study else 0
        print(f"  Data Entries: {total_kp} | Check Items: {total_q} | "
              f"Risk Cases: {total_cs}")

        if not self.api_key:
            print("  [!] DEEPSEEK_API_KEY 未配置")
            print("  [!] 数据样本仅显示标准数据，不做AI评分")
            print("  [!] 配置方法: 编辑 esg_engine.py 中的 DEEPSEEK_API_KEY")
            print("  [!] 获取地址: https://platform.deepseek.com/")

        print("=" * 60)

        # Calculate phase boundaries for display
        kp_end = total_kp
        q_end = kp_end + total_q

        while 0 <= self.idx < len(self.items):
            item_type, item_data = self.items[self.idx]

            # Show phase header when entering a new phase
            if self.idx == 0 and total_kp > 0:
                print(f"\n  [Phase 1] Data Entry Review ({total_kp} items)")
            elif self.idx == kp_end and total_q > 0:
                print(f"\n  [Phase 2] Validation Checklist ({total_q} items)")
            elif self.idx == q_end and total_cs > 0:
                print(f"\n  [Phase 3] Risk Assessment Case")

            if item_type == "knowledge_point":
                action = self.review_knowledge_point(
                    item_data, self.idx, len(self.items))
            elif item_type == "question":
                # Adjust index display to show question-relative position
                q_idx = self.idx - kp_end
                action = self.review_question(
                    item_data, q_idx, total_q)
            elif item_type == "case_study":
                action = self.review_case_study(item_data)
            else:
                action = "next"

            if action == "quit":
                self.show_summary()
                self._save_progress()
                return
            elif action == "prev":
                self.idx = max(0, self.idx - 1)
            else:
                self.idx += 1

        self.show_summary()
        self._save_progress()


# ===========================================================================
# CONVENIENCE: Run directly for testing
# ===========================================================================

if __name__ == "__main__":
    # When run directly, load from question_bank.json and do a quick quiz
    print("Loading question bank...")
    by_kp, all_questions = load_question_bank()

    if not all_questions:
        print("No questions found. Make sure question_bank.json is in the same directory.")
        sys.exit(1)

    # Select a small sample for quick test
    import random
    sample = random.sample(all_questions, min(8, len(all_questions)))

    session = StudySession(
        knowledge_points=[],
        questions=sample,
        case_study=None,
    )
    session.run()
