#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Sample Daily Study Script (示例每日学习脚本)
Data Validation / Configuration Audit Module
Auto-generated by data-pipeline-tools

Usage:
    python sample_study.py           # Full session (knowledge + quiz + case)
    python sample_study.py review    # Knowledge points only
    python sample_study.py quiz      # Questions only (all 4 types)
    python sample_study.py case      # Case study only (DeepSeek graded)

Navigation:
    [P]         - Previous item (works across all phases)
    [N]/Enter   - Next item
    [Q]         - Quit and show summary
    [1]         - Mark as mastered
    [2]         - Mark as needs review
    [3]         - Show explanation/answer
    [0]         - Skip
"""

import os
import sys
import json
import datetime

# ===========================================================================
# API CONFIGURATION
# ===========================================================================
# Fill in your DeepSeek API key to enable AI grading for short-answer questions.
# Get your key at: https://platform.deepseek.com/
# If left empty, short-answer questions will skip AI grading.
DEEPSEEK_API_KEY = ""  # <-- 首次使用skill时由用户填写  # <-- Replace with your key, e.g. "sk-xxxxxxxx"

# ===========================================================================
# CONTENT SELECTION
# ===========================================================================

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

def load_json(filename):
    """Load JSON from the script's directory."""
    path = os.path.join(SCRIPT_DIR, filename)
    if not os.path.exists(path):
        print(f"  [!] File not found: {path}")
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def select_knowledge_points(kb_data, count=10):
    """Select knowledge points, rotating based on today's date.

    Each day covers different knowledge points, cycling through all 74 over
    approximately 8 days.
    """
    all_kps = kb_data.get("knowledge_points", [])
    if not all_kps:
        return []

    today = datetime.date.today()
    day_offset = today.toordinal() % max(1, len(all_kps))

    # Rotate starting point each day, select 'count' items
    selected = []
    for i in range(count):
        idx = (day_offset + i) % len(all_kps)
        selected.append(all_kps[idx])
    return selected


def select_questions(qb_data, count=10, kp_refs=None, progress_data=None, exclude=None):
    """Select questions by learning progress: unanswered first, then low-accuracy,
    then least-practiced. Falls back to balanced type mix.
    """
    import random
    all_qs = qb_data.get("questions", [])
    if not all_qs:
        return []

    today = datetime.date.today()
    random.seed(today.toordinal())

    # Progress-aware selection (when progress data exists)
    if progress_data is not None:
        try:
            import progress_store
            selected = progress_store.select_questions(
                progress_data, all_qs, count, exclude=exclude or set())
            if len(selected) >= count:
                return selected[:count]
        except Exception:
            pass

    # Fallback: balanced type mix (original behavior)
    by_type = {}
    for q in all_qs:
        t = q["type"]
        if t not in by_type:
            by_type[t] = []
        by_type[t].append(q)

    per_type = max(1, count // 4)
    remainder = count - per_type * 4

    selected = []
    for qtype in ["single_choice", "multiple_choice", "true_false", "short_answer"]:
        pool = by_type.get(qtype, [])
        random.shuffle(pool)

        if kp_refs:
            linked = [q for q in pool if q.get("kp_ref") in kp_refs]
            others = [q for q in pool if q.get("kp_ref") not in kp_refs]
            pick = linked + others
        else:
            pick = pool

        n = per_type + (1 if remainder > 0 else 0)
        remainder -= 1
        selected.extend(pick[:n])

    return selected[:count]


# ===========================================================================
# CASE STUDY
# ===========================================================================

CASE_STUDY = {
    "id": "CASE-001",
    "level": "intermediate",
    "background": (
        "某制造企业发布ESG报告称已实现'碳中和', 但经核查发现:\n"
        "1. 仅计算了Scope 1排放, 未包含Scope 2和Scope 3\n"
        "2. 大量依赖碳抵消项目, 未说明项目质量\n"
        "3. 未提供第三方验证"
    ),
    "requirements": [
        "指出该报告存在的'漂绿'风险点",
        "说明应如何改进披露",
        "引用相关标准框架进行说明",
    ],
    "reference_answer": (
        "1. 漂绿风险点:\n"
        "   - 排放范围不完整: 仅Scope 1, 遗漏Scope 2(外购能源)和Scope 3(价值链)\n"
        "   - 碳抵消不透明: 未披露抵消项目类型、验证标准(如VCS, Gold Standard)\n"
        "   - 缺乏独立鉴证: 无第三方审计, 数据可信度存疑\n"
        "2. 改进建议:\n"
        "   - 按GHG Protocol全面核算三个范围的排放\n"
        "   - 优先减排, 谨慎使用碳抵消, 披露抵消项目详情\n"
        "   - 引入第三方鉴证, 提高数据可靠性\n"
        "3. 相关标准: GRI(影响重要性), ISSB IFRS S2(气候披露), TCFD(四大支柱)"
    ),
    "scoring_points": [
        "识别排放范围不完整的漂绿风险(Scope 1/2/3)",
        "识别碳抵消不透明的风险",
        "识别缺乏第三方验证的风险",
        "提出按GHG Protocol全面核算的改进建议",
        "提出引入第三方鉴证的改进建议",
        "引用GRI/ISSB/TCFD等标准框架",
    ],
    "kp_refs": ["ESG-H-001", "ESG-H-007", "ESG-H-008", "ESG-H-009"],
}


# ===========================================================================
# MAIN
# ===========================================================================

def main():
    mode = "full"
    if len(sys.argv) > 1:
        mode = sys.argv[1].lower()

    # Import the engine
    sys.path.insert(0, SCRIPT_DIR)
    from esg_engine import StudySession

    # Load data
    kb_data = load_json("knowledge_base.json")
    qb_data = load_json("question_bank.json")

    if not qb_data:
        print("Cannot find question_bank.json. Make sure it's in the same directory.")
        sys.exit(1)

    # Load learning progress (用于智能选题与记录)
    try:
        import progress_store
        progress_data = progress_store.load_progress()
    except Exception:
        progress_data = None

    # Select content based on mode
    knowledge_points = []
    questions = []
    case_study = None
    session_exclude = set()  # 本会话已用题目(避免重复)

    if mode in ("full", "review"):
        kp_count = 10 if mode == "full" else 15
        knowledge_points = select_knowledge_points(kb_data or {}, count=kp_count)
        print(f"  Selected {len(knowledge_points)} knowledge points")

    if mode in ("full", "quiz"):
        kp_refs = set(kp["id"] for kp in knowledge_points) if knowledge_points else None
        questions = select_questions(qb_data, count=10, kp_refs=kp_refs,
                                     progress_data=progress_data, exclude=session_exclude)
        session_exclude.update(q["id"] for q in questions)
        print(f"  Selected {len(questions)} questions (progress-aware)")

    if mode in ("full", "case"):
        case_study = CASE_STUDY

    if mode == "review" and not knowledge_points:
        print("No knowledge points available.")
        sys.exit(1)
    if mode == "quiz" and not questions:
        print("No questions available.")
        sys.exit(1)

    # Create and run session (进度记录开启)
    session = StudySession(
        knowledge_points=knowledge_points,
        questions=questions,
        case_study=case_study,
        api_key=DEEPSEEK_API_KEY,
        progress_data=progress_data,
    )
    session.run()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n  [Interrupted] Session data saved.")
        sys.exit(0)
